Show board outliers in calibration info card
PhotonVision/photonvision pull request #1267
Opened 2024-03-06 06:15 UTC by mcm001

Pipes back to photon directly mrcal outliers and optimized board pose. Goes with https://github.com/PhotonVision/mrcal-java/pull/4/ and requires https://github.com/PhotonVision/photonvision/pull/2214

<img width="1348" height="677" alt="image" src="https://github.com/user-attachments/assets/002f3029-78bb-44a3-8d2f-5ee9b93e40c7" />

<img width="1940" height="908" alt="image" src="https://github.com/user-attachments/assets/8038c580-6716-483c-a489-3e7a1a5c2e32" />

<img width="1076" height="946" alt="image" src="https://github.com/user-attachments/assets/0d444264-f1cc-47be-88be-ae8d327d0bf1" />

Reprojection error data on main vs this MR, including a fix for "false" (opencv) charuco boards where we weren't ignoring ignored corners:

| Main                                                                                                                               | Main                                        | Matt's MR                                   |
| ---------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------- | ------------------------------------------- |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [1] SQUARES_LIFECAM_480, true STANDARD_OUT               | RMS Reprojection Error: 0.38192536506598534 | RMS Reprojection Error: 0.33577593512471376 |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [2] SQUARES_LIFECAM_480, false STANDARD_OUT              | RMS Reprojection Error: 1.0580504936756594  | RMS Reprojection Error: 1.0580504936756594  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [3] SQUARES_LIFECAM_1280, true STANDARD_OUT              | RMS Reprojection Error: 0.8168208100792993  | RMS Reprojection Error: 0.7159327531283418  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [4] SQUARES_LIFECAM_1280, false STANDARD_OUT             | RMS Reprojection Error: 2.0494151762764936  | RMS Reprojection Error: 2.0494151762764936  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [5] CHARUCO_LIFECAM_480, true STANDARD_OUT               | RMS Reprojection Error: 0.3072208877612695  | RMS Reprojection Error: 0.2975728236616564  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [6] CHARUCO_LIFECAM_480, false STANDARD_OUT              | RMS Reprojection Error: 1009.3690116953635  | RMS Reprojection Error: 0.5127304814432004  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [7] CHARUCO_LIFECAM_1280, true STANDARD_OUT              | RMS Reprojection Error: 0.5319664503422203  | RMS Reprojection Error: 0.5373510159628804  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [8] CHARUCO_LIFECAM_1280, false STANDARD_OUT             | RMS Reprojection Error: 18256.975012936167  | RMS Reprojection Error: 1.0127259170530452  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [9] CHARUCO_OLDPATTERN_LIFECAM_480, true STANDARD_OUT    | RMS Reprojection Error: 0.39632201737448564 | RMS Reprojection Error: 0.36835572504426434 |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [10] CHARUCO_OLDPATTERN_LIFECAM_480, false STANDARD_OUT  | RMS Reprojection Error: 1282.37016241995    | RMS Reprojection Error: 0.822132764305405   |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [11] CHARUCO_OLDPATTERN_LIFECAM_1280, true STANDARD_OUT  | RMS Reprojection Error: 0.5545049332256538  | RMS Reprojection Error: 0.5568386572683223  |
| Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [12] CHARUCO_OLDPATTERN_LIFECAM_1280, false STANDARD_OUT | RMS Reprojection Error: 1315.1252803237867  | RMS Reprojection Error: 1.5874786318023275  |

2025-11-01 22:23 UTC, Gold856 commented on photon-server/src/main/java/org/photonvision/Main.java
Why are all these changes here? Can some of them be moved to another PR if we still want them?

2025-11-01 22:23 UTC, Gold856 commented on photon-server/src/main/java/org/photonvision/server/RequestHandler.java
> +                    kObjectMapper.readValue(ctx.req().getInputStream(), DataCalibrationImportRequest.class);
Unrelated?

2025-11-01 22:25 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/FindBoardCornersPipe.java
I'm trusting you on this. I lack the domain knowledge to verify this is correct.

2025-11-01 22:37 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +                                + expected;
Assertions are disabled by default

2025-11-01 22:38 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/jni/PhotonJNICommon.java
Why so many removals of var?

2025-11-01 22:39 UTC, Gold856 commented on photon-client/src/components/cameras/CameraCalibrationInfoCard.vue
> +
This should be unnecessary

2025-12-05 05:55 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/server/RequestHandler.java
> +                    kObjectMapper.readValue(ctx.req().getInputStream(), DataCalibrationImportRequest.class);
No -- this actually works around a body size limitation in Jackson I believe. This lets you upload JSONs that are larger than our maximum otherwise would allow. `body()` reads the whole body into a String, then hands that whole String off to Jackson. Giving Jackson the InputStream itself cuts out a middle man

2025-12-05 05:56 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +                                + expected;
swapped to an exception

2025-12-05 05:57 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/jni/PhotonJNICommon.java
Not sure there's a compelling reason. We should probably not change what we don't have to.

2025-12-05 05:57 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/jni/PhotonJNICommon.java
arguably all this needs to move into its own MR -- it's totally unrelated

2025-12-05 05:59 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/Main.java
moving the log level to the top was helpful while debugging library loading -- do you want it to move?

2025-12-05 06:01 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/FindBoardCornersPipe.java
Looks like this MR is failing tests anyways, so we need to do more homework

```
Calibrate3dPipeTest > calibrateTestMatrix(CalibrationDatasets, boolean) > [12] CHARUCO_OLDPATTERN_LIFECAM_1280, false FAILED
    java.lang.RuntimeException: Negative corner in reprojection error calc! Measured: {-7218.59521484375, -6922.4638671875}, expected: {-1.0, -1.0}
        at org.photonvision.vision.pipe.impl.Calibrate3dPipe.createObservations(Calibrate3dPipe.java:408)
        at org.photonvision.vision.pipe.impl.Calibrate3dPipe.calibrateOpenCV(Calibrate3dPipe.java:208)
        at org.photonvision.vision.pipe.impl.Calibrate3dPipe.process(Calibrate3dPipe.java:108)
        at org.photonvision.vision.pipe.impl.Calibrate3dPipe.process(Calibrate3dPipe.java:44)
        at org.photonvision.vision.pipe.CVPipe.run(CVPipe.java:54)
        at org.photonvision.vision.pipeline.Calibrate3dPipeline.tryCalibration(Calibrate3dPipeline.java:190)
        at org.photonvision.vision.pipeline.Calibrate3dPipeTest.calibrateCommon(Calibrate3dPipeTest.java:256)
        at org.photonvision.vision.pipeline.Calibrate3dPipeTest.calibrateCommon(Calibrate3dPipeTest.java:161)
        at org.photonvision.vision.pipeline.Calibrate3dPipeTest.calibrateTestMatrix(Calibrate3dPipeTest.java:145)
```

2025-12-06 05:09 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/jni/PhotonJNICommon.java
Moved to https://github.com/PhotonVision/photonvision/pull/2219

2025-12-06 05:53 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/mrcal/MrCalJNILoader.java
> -/*
Blocking comment to merge https://github.com/PhotonVision/photonvision/pull/2214 first

2025-12-06 05:55 UTC, Gold856 commented on photon-client/src/components/app/photon-3d-visualizer.vue
> +    console.log("Drawing camera frustum with calibration coeffs:", calibrationCoeffs);
Remove console.log

2025-12-06 05:57 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    const isActive = !obs.cornersUsed[idx];
This name doesn't really make sense to me.

2025-12-06 05:58 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  if (!cal || scene === undefined || camera === undefined || renderer === undefined || controls === undefined) {
Simplify check by negating all objects.

2025-12-06 05:59 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  const aspect = imageWidth / imageHeight;
Should this math be factored out? I've seen it twice now.

2025-12-06 06:03 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  if (container === null || canvas === null || camera === undefined || renderer === undefined) {
Simplify checks by negating objects.

2025-12-06 06:03 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  if (scene === undefined || camera === undefined || controls === undefined) {
Ditto

2025-12-06 06:04 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    return;
Ditto

2025-12-06 06:04 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  if (canvas === null) return;
Ditto

2025-12-06 06:05 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    if (scene === undefined || camera === undefined || renderer === undefined || controls === undefined) {
Aaaaa

2025-12-06 06:08 UTC, Gold856 commented on photon-client/src/components/cameras/CameraCalibrationCard.vue
> +                </tr>
You know the drill.

2025-12-06 06:13 UTC, Gold856 commented on photon-server/src/main/java/org/photonvision/Main.java
I mean, I don't particularly care. Was wondering why though, because it looked superficial. We can keep it.

2025-12-06 06:13 UTC, mcm001 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    const isActive = !obs.cornersUsed[idx];
I wasn't sure what the inverse of an outlier is. Is "isInlier" better?

2025-12-06 06:16 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    const isActive = !obs.cornersUsed[idx];
That's the same term you use in BoardObservations, although apparently the definition of inliner is just an unusual data point that's actually in the range of normal data.

It's mostly weird to me because it's called `isActive` but then negates an array element from an array named `cornersUsed`.

2025-12-06 06:33 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
Use `toList()` instead of `collect(Collectors.toList()`

2025-12-06 07:19 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
This one's all over the codebase as well -- maybe find and replace in a separate ME if we want to change code style?

2025-12-06 07:49 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
Okay, done. PR https://github.com/PhotonVision/photonvision/pull/1830 submitted 9 months ago, merged 8 months ago.

2025-12-06 17:32 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
<img width="424" height="392" alt="image" src="https://github.com/user-attachments/assets/ea13e0ed-fbe1-4dd7-b3a0-1554cc18ad52" />
(and yet)

Also, I cannot do that here. objPoints is a List<Mat>, but it.objectPoints is a MatOfPoint2f, so this results in a compiler error.

2025-12-06 22:08 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
(it's because `toList()` creates an immutable `List` and in those cases it either needed mutability or I couldn't prove nobody was relying on that mutability)
Oh right, I remember trying to convert this before and failing because of the types used here. Taking a second look at it, I think the `List` type parameter should actually use the type of the points instead of `Mat`, and that change should be propagated through `createObservations`. There's some casting and copying in `createObservations` that could be removed if you propagate that.

2025-12-06 22:57 UTC, Gold856 commented on photon-client/src/types/SettingTypes.ts
> +  numMissing: number[];
Flip the order here to match the Java class

2025-12-07 01:00 UTC, mcm001 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  const aspect = imageWidth / imageHeight;
Sure, sounds reasonable. done fcfaf43062b5f6670ce28d2747f269a3894dd857

2025-12-07 01:03 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
> There's some casting and copying in createObservations that could be removed if you propagate that.

I actually don't want to mutate the underlying objPoints when applying board warp, so I'll need to keep that indirection, but i agree it's cleaner without

2025-12-07 01:44 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
Mutation is fine, since that list is never used again afterwards. Is that an important invariant to hold up?

2025-12-07 01:47 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
Because java (the language) makes it hard for me to have the compiler audit for any spooky action at a distance this modification in place may cause, I'm scared of double-warping object points.

2025-12-07 01:53 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/pipe/impl/Calibrate3dPipe.java
> +        List<Mat> imgPts = in.stream().map(it -> it.imagePoints).collect(Collectors.toList());
Fair enough. I'll leave the copy, but I'll switch to `toList()`. The rest of the type propagation looks good to me.

2025-12-07 02:00 UTC, Gold856 requested changes

2025-12-07 02:00 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +// If not-reloadeing, cleanup on hot reload
Typo

2025-12-07 02:00 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +    <!-- <template v-if="calibrationData"> -->
Remove commented out code

2025-12-07 02:00 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  controls.target.set(0.0, 0.0, 1.0);
Lots of magic numbers here and in the 3rd person variant.

2025-12-07 18:01 UTC, mcm001 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  controls.target.set(0.0, 0.0, 1.0);
I'm not sure if extracting these magic numbers to constants is valuable -- they were determined heuristically (they seem to look good to me). Is pulling them out really helpful?

2025-12-08 01:29 UTC, Gold856 commented on photon-client/src/components/app/photon-calibration-visualizer.vue
> +  controls.target.set(0.0, 0.0, 1.0);
Mostly just taking note of them. If it's just "it looks good" and we can just leave it.

2025-12-12 00:28 UTC, Gold856 requested changes

2025-12-12 00:28 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +        int thickness = Core.FILLED;
Inline this since it's only used once.

2025-12-12 00:28 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +     * @return
What's it return?

2025-12-12 00:28 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +     * @return
What's it return?

2025-12-12 00:28 UTC, Gold856 commented on photon-client/src/lib/ThreeUtils.ts
> + * @returns
What's it return?

2025-12-13 19:15 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +        int thickness = Core.FILLED;
Splitting this out is actually helpful in making what the magic goop I've got to calculate r is more readable imo?

2025-12-13 23:30 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +        int thickness = Core.FILLED;
Fair enough.

2025-12-19 07:12 UTC, DevonRD commented
cleaned up target tab, fixed calibration visualizer resizing, and made both calibration and 3d visualizers conform to theme
<img width="1266" height="584" alt="image" src="https://github.com/user-attachments/assets/c96b55d1-c735-4217-b0aa-3761f76cd14f" />

2025-12-19 07:25 UTC, samfreund commented
Needs docs. Perhaps a little info icon that users can hover over to explain the general premise then more in depth on the docs page.

The first person viewer is wack, I would do third-person only.

View calibration information popup updates too slowly 
[Screencast from 12-19-2025 01:24:58 AM.webm](https://github.com/user-attachments/assets/b4189a85-f880-4325-85e5-4ca4bad410c1)

2025-12-19 07:42 UTC, Gold856 requested changes

2025-12-19 07:42 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +     * mean is calcualted as the mean of each individual corner's reprojection error, or the distance
Typo

2025-12-19 07:42 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +            return null;
Does `imread` even throw an exception? It seems to just return an empty `Mat` instead, in which case a lot of this logic can be simplified down to checking if it's empty, and returning null there, otherwise return the result of `imread`.

2025-12-20 02:50 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +            return null;
I don't know what guarantees we have about native code never throwing through the JNI, although research indicates that your read is correct. Can you point to any docs that say it shall never throw?

2025-12-20 02:56 UTC, Gold856 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +            return null;
https://docs.opencv.org/4.10.0/javadoc/org/opencv/imgcodecs/Imgcodecs.html#imread(java.lang.String,int) and https://docs.opencv.org/4.10.0/d4/da8/group__imgcodecs.html#gab32ee19e22660912565f8140d0f675a8 both list potential error conditions (missing file, etc) as just returning an empty Mat, no exceptions thrown, especially on the C++ side, where it seems like [C++ exceptions are mapped to Java exceptions](https://github.com/opencv/opencv/blob/4.x/modules/java/generator/gen_java.py#L1111).

2025-12-20 02:59 UTC, mcm001 commented on photon-core/src/main/java/org/photonvision/vision/calibration/BoardObservation.java
> +            return null;
Let's change this back then. It would be neat to get the cal code into the new playwright tests so we can do this drawing in CI but not going to block this on that

2025-12-27 00:17 UTC, Gold856 approved these changes

2025-12-27 02:20 UTC, merged