Only report actually active cameras in PhotonCamera error print
PhotonVision/photonvision pull request #1298
Opened 2024-03-22 02:26 UTC by mcm001

Previously reported itself which was confusing. New print:

```
Error at org.photonvision.PhotonCamera.verifyVersion(PhotonCamera.java:378): Found the following PhotonVision cameras active on NetworkTables:
 ==> HD_Pro_Webcam_C920
 ==> Arducam_OV9281_USB_Camera
```

2024-03-22 03:00 UTC, srimanachanta requested changes

2024-03-22 03:00 UTC, srimanachanta commented on photon-lib/src/main/java/org/photonvision/PhotonCamera.java
> +                        "Found the following PhotonVision cameras active on NetworkTables:\n"
They aren't necessarily active cause they are on NT, just present. I think this should be left as is.

2024-03-22 03:00 UTC, srimanachanta commented on photon-lib/src/main/java/org/photonvision/PhotonCamera.java
> +    MultiSubscriber m_topicNameSubscriber;
nit: match camelCase naming convention

2024-05-10 16:02 UTC, gerth2 approved these changes

2024-05-10 18:58 UTC, merged