Disable Arm32 Builds
PhotonVision/photonvision pull request #1325
Opened 2024-05-19 14:39 UTC by Craftzman7

As requested in the [Discord](https://discord.com/channels/725836368059826228/725846784131203222/1241759253258047518) this PR disables Arm32 builds and removes mention of the build option in the README.

2024-05-19 14:45 UTC, Bankst approved these changes

2024-05-19 14:48 UTC, mcm001 commented
Closes #1324

2024-05-19 14:49 UTC, mcm001 approved these changes
🛥️

2024-05-19 19:54 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/Main.java
> +                System.exit(0);
Nit for future: why do we exit 0 on failure?

2024-05-19 19:54 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/Main.java
> +        if (!Platform.isSupported() && !isSmoketest) {
Smoke test and test mode are two different things. We want this check to be skipped on both.

2024-05-19 23:24 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/Main.java
> +                System.exit(0);
If you wanna exit 1 or something with a error print now, sure

2024-05-19 23:24 UTC, mcm001 requested changes

2024-05-19 23:24 UTC, mcm001 commented on photon-server/src/main/java/org/photonvision/Main.java
> +        if (!Platform.isSupported() && (!isSmoketest || !isTestMode)) {
I would double check your Boolean logic here...

2024-05-20 00:35 UTC, mcm001 approved these changes

2024-05-20 00:35 UTC, merged