Remove wpilibc dependency from vendordep JSON
PhotonVision/photonvision pull request #1543
Opened 2024-11-10 04:20 UTC by Gold856

JNI shouldn't be linking to wpilibc (cause it also loads things that wpilibj loads.)

2024-11-10 04:20 UTC, spacey-sooty approved these changes

2024-11-10 04:21 UTC, mcm001 commented
Hold yer horses. I need to load wpilibc

2024-11-10 04:21 UTC, spacey-sooty commented
> Hold yer horses. I need to load wpilibc

Not for JNI you shouldn't?? why?

2024-11-10 04:21 UTC, mcm001 requested changes
So I do need to load wpilibc. photon-targeting links to wpililbc.

2024-11-10 04:24 UTC, Gold856 commented
The JNI part loads wpilibc? The C++-only component might, but the JNI part seems like it doesn't.

2024-11-10 04:25 UTC, mcm001 commented
Well either way, for a Java robot project, we need to deploy wpilibc.dll

2024-11-10 04:27 UTC, spacey-sooty commented
> photon-targeting uses the wpinet libuv stuff is why, iirc?
that is all seperately linked to wpilibc

2024-11-10 04:28 UTC, spacey-sooty commented
> The JNI part loads wpilibc? The C++-only component might, but the JNI part seems like it doesn't.

photon-targetting-cpp is listed as a JNI dependency...

2024-11-10 04:31 UTC, spacey-sooty commented
> Well either way, for a Java robot project, we need to deploy wpilibc.so.

Why? You shouldn't have to...

2024-11-14 05:27 UTC, Gold856 commented
OBE by #1544

2024-11-14 05:27 UTC, closed without merging