Send corners of min area rectangles
PhotonVision/photonvision pull request #382
Opened 2022-01-09 22:43 UTC by mcm001

2022-01-09 22:54 UTC, calcmogul requested changes

2022-01-09 22:54 UTC, calcmogul commented on photon-lib/src/main/native/cpp/photonlib/PhotonTrackedTarget.cpp
> +    target.corners.push_back(std::make_pair(first, second));
```suggestion
    target.corners.emplace_back(first, second);
```

2022-01-09 22:54 UTC, calcmogul commented on photon-lib/src/main/native/cpp/photonlib/SimVisionSystem.cpp
> +            std::make_pair(7,8)});
Prefer `std::pair{1.0, 2.0}` over `std::make_pair(1.0, 2.0)`.

2022-01-09 22:54 UTC, calcmogul commented on build.gradle
> + targets   }
Remove this.

2022-01-10 02:46 UTC, calcmogul commented
You need to run spotless.

2022-01-11 01:42 UTC, Bankst requested changes

2022-01-11 01:42 UTC, Bankst commented on photon-server/src/main/resources/web/index.html
> +<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon
bade

2022-01-11 01:55 UTC, mcm001 commented on photon-server/src/main/resources/web/index.html
> +<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=icon href=/favicon
aaaaaaaaaaaaaaaaaa

2022-01-11 04:21 UTC, Bankst approved these changes

2022-01-11 04:31 UTC, merged