update documentation
PhotonVision/photonvision pull request #740
Opened 2023-01-15 00:14 UTC by srimanachanta

2023-01-15 00:27 UTC, mdurrani808 requested changes

2023-01-15 00:27 UTC, mdurrani808 commented on photon-lib/src/main/java/org/photonvision/PhotonPoseEstimator.java
> + * The PhotonPoseEstimator class filters or combines readings from all the fiducial targets visible
Why not just say apriltag for clrarity

2023-01-15 00:27 UTC, mdurrani808 commented on photon-lib/src/main/java/org/photonvision/PhotonPoseEstimator.java
> +     * @param fieldTags A WPILib {@link AprilTagFieldLayout} linking AprilTag IDs to Pose3d objects
link to wpilib field coordinate system page. also dont know why there is the abbreviation

2023-01-15 00:52 UTC, mcm001 commented on photon-lib/src/main/java/org/photonvision/PhotonPoseEstimator.java
> + * The PhotonPoseEstimator class filters or combines readings from all the April Tags visible at a
AprilTag is one word

2023-01-18 01:33 UTC, mcm001 approved these changes

2023-01-18 01:34 UTC, merged