[PhotonPoseEstimator] Check for CalibData before adding Tags when using SolvePNP method
PhotonVision/photonvision pull request #826
Opened 2023-03-06 16:34 UTC by srimanachanta

closes #825

2023-04-19 13:38 UTC, mcm001 commented
In what way does this optimize the function? Both a list of valid targets and valid calibration data are necessary preconditions for solvePNP being run

2023-04-19 15:06 UTC, srimanachanta commented
> In what way does this optimize the function? Both a list of valid targets and valid calibration data are necessary preconditions for solvePNP being run

Yeah, more of just a reorder, because it checks if PNP is possible due to the calibration matrices before adding the poses to arrays, and checking the field layout for the tags, it could simplify some of the logic

2023-06-11 00:55 UTC, mcm001 approved these changes

2023-06-16 17:24 UTC, mcm001 requested changes

2023-06-16 17:24 UTC, mcm001 commented on photon-lib/src/main/java/org/photonvision/PhotonPoseEstimator.java
> +            return Optional.empty();
Needs to be `return update(result, cameraMatrixOpt, distCoeffsOpt, this.multiTagFallbackStrategy);`

2023-06-16 17:24 UTC, mcm001 commented on photon-lib/src/main/native/cpp/photonlib/PhotonPoseEstimator.cpp
> +    return std::nullopt;
Also needs to be changed to `return Update(result, std::nullopt, std::nullopt,
                  this->multiTagFallbackStrategy);`

2023-06-18 03:47 UTC, mcm001 approved these changes

2023-06-18 04:00 UTC, merged