Bump to beta 2
PhotonVision/photonvision pull request #972
Opened 2023-10-20 22:58 UTC by mcm001

2023-10-20 23:02 UTC, mdurrani808 commented
would it be possible to just make those all one big global variable so you just need to update it in one place or does it not work like that

2023-10-20 23:07 UTC, srimanachanta commented
Bump gradle to 8.4 while you are at it

2023-10-21 14:38 UTC, srimanachanta requested changes

2023-10-21 14:38 UTC, srimanachanta commented on photonlib-cpp-examples/apriltagExample/simgui-window.json
This file should be unchanged

2023-10-21 14:38 UTC, srimanachanta commented on shared/common.gradle
> +    // wpilib serde
stuff?

2023-10-21 14:42 UTC, mcm001 commented on shared/common.gradle
> +    // wpilib serde
serde. Serialization/deserialization

2023-10-24 01:49 UTC, srimanachanta approved these changes

2023-10-24 03:28 UTC, merged